Repository team-eeats/eeats-fe, pull requests merged in 2024-09, with the labels that each got.

#7 사진 투표 컴포넌트 개발
  src/Components/ConpletePhotoVote/index.tsx
  src/Components/ConpletePhotoVote/styled.ts
  src/Components/PhotoVote/index.tsx
  src/Components/PhotoVote/styled.ts
  src/Components/index.js
  src/assets/img/PNG/chobab.png
  src/assets/img/PNG/dakgalbi.jpg
  src/assets/img/PNG/ddeokbokki.png
  src/assets/img/PNG/malatang.png
  src/assets/img/SVG/VoteConplete.svg
  src/router.tsx
Labels: 퍼블리싱

#8 ✨:: 메인페이지 급식 정보 컴포넌트 개발
  src/Components/AllergyNotification/AllergyNotification.tsx
  src/Components/AllergyNotification/NoAllergy.tsx
  src/Components/AllergyNotification/Styled.ts
  src/Components/MealList/BreakfastList.tsx
  src/Components/MealList/DinnerList.tsx
  src/Components/MealList/LunchList.tsx
  src/Components/MealList/Styled.ts
  src/Components/MealTime/MealTime.tsx
  src/Components/MealTime/Styled.ts
  src/Styles/Font.tsx
  src/assets/img/Breakfast.svg
  src/assets/img/Dinner.svg
  src/assets/img/Lunch.svg
  src/router.tsx
Labels: 퍼블리싱

#9 💄 :: 공지사항 메세지 컴포넌트 퍼블리싱
  src/Components/Notice/Message.tsx
  src/Components/Notice/index.ts
  src/assets/img/Message.svg
  src/assets/img/NewMark.svg
Labels: 퍼블리싱

#12 투표 종류 확인 컴포넌트
  src/Components/VoteType/index.tsx
  src/Components/VoteType/style.ts
Labels: 퍼블리싱

#16 알레르기 태그 만들기
  src/Components/AllergyTags/index.tsx
  src/Components/AllergyTags/style.ts
Labels: 퍼블리싱

#17 ✨:: 도넛 그래프 개발
  package.json
  src/Components/DonutGraph/index.tsx
  src/Components/DonutGraph/styled.ts
  src/router.tsx
  yarn.lock
Labels: 퍼블리싱

#20 버튼 컴포넌트 만들기
  src/Components/Button/index.tsx
  src/Components/Button/style.ts
Labels: 퍼블리싱

#21 탭 컴포넌트 퍼블리싱
  src/Components/TabNavigation/Navigation.tsx
  src/Components/TabNavigation/TabBar.tsx
  src/Components/TabNavigation/style.ts
  src/Styles/index.css
  src/assets/img/SVG/HomeIcon.tsx
  src/assets/img/SVG/HomeWhiteIcon.tsx
  src/assets/img/SVG/SuggestIcon.tsx
  src/assets/img/SVG/SuggestWhiteIcon.tsx
  src/assets/img/SVG/VoteIcon.tsx
  src/assets/img/SVG/VoteWhiteIcon.tsx
  src/assets/img/SVG/index.ts
  src/router.tsx
Labels: 퍼블리싱

#19 Input 컴포넌트 개발
  src/Components/Input/Input.tsx
  src/Components/Input/Style.ts
  src/assets/img/SVG/CloseEyes.svg
  src/assets/img/SVG/OpenEyes.svg
Labels: 퍼블리싱

#23 기능 변경
  src/Components/Button/index.tsx
  src/Components/Button/style.ts
Labels: 리팩토링, 퍼블리싱

#30 input component zustand 사용해서 상태 관리하기
  src/Components/Input/Input.tsx
  src/store/useInputStore.ts
Labels: 리팩토링, 퍼블리싱

#31 캘린더 퍼블리싱 및 기능 추가
  package-lock.json
  src/Components/Calendar/index.tsx
  src/Components/Calendar/style.ts
  src/assets/img/SVG/ArrowLeft.tsx
  src/assets/img/SVG/ArrowRight.tsx
  src/assets/img/SVG/index.ts
  src/router.tsx
  yarn.lock
Labels: 퍼블리싱

#34 Login page 만들기
  src/Components/Input/Input.tsx
  src/page/index.ts
  src/page/loginPage/index.tsx
  src/page/loginPage/style.ts
  src/store/useInputStore.ts
Labels: 퍼블리싱

#33 input 값 공유되는 거 수정
  src/Components/Input/Input.tsx
  src/store/useInputStore.ts
Labels: 리팩토링, 퍼블리싱

#39 🎨 :: 텍스트 투표 수정하기
  src/Components/TextVote/index.tsx
  src/Components/TextVote/style.ts
Labels: 리팩토링, 퍼블리싱

#40 건의 페이지
  src/Components/CheckCancelButton/index.tsx
  src/Components/CheckCancelButton/style.ts
  src/Components/DeleteModal/index.tsx
  src/Components/DeleteModal/style.ts
  src/Components/Layout.tsx
  src/Components/ModifyDeleteModal/index.tsx
  src/Components/ModifyDeleteModal/style.ts
  src/Components/UserSuggestBox/index.tsx
  src/Components/UserSuggestBox/style.ts
  src/Pages/Suggest/Modify.tsx
  src/Pages/Suggest/Upload.tsx
  src/Pages/Suggest/index.tsx
  src/Pages/Suggest/style.ts
  src/assets/img/ArrowRight.svg
  src/assets/img/SVG/Write.svg
  src/assets/img/Setting.svg
  src/router.tsx
Labels: 퍼블리싱

#41 ✨:: 닉네임 변경 모달 퍼블리싱
  src/Components/Header/index.tsx
  src/Components/Header/style.ts
  src/Components/NicknameChange/index.tsx
  src/Components/NicknameChange/style.ts
  src/router.tsx
Labels: 퍼블리싱

#42 ✨ :: 투표 페이지 만들기
  src/Components/VoteType/style.ts
  src/page/votePage/index.tsx
  src/page/votePage/style.ts
  src/router.tsx
Labels: 퍼블리싱

#43 마이페이지, 알림 모달 퍼블리싱
  src/Components/AlarmModal/index.tsx
  src/Components/AlarmModal/styled.ts
  src/Components/MyAllergy/index.tsx
  src/Components/MyAllergy/style.ts
  src/Components/MyPageModal/index.tsx
  src/Components/MyPageModal/styled.ts
  src/Styles/Font.tsx
  src/assets/img/SVG/Logout.svg
  src/assets/img/SVG/Medicine.svg
  src/assets/img/SVG/Notice.svg
  src/assets/img/SVG/Suggest.svg
Labels: 퍼블리싱

#48 🎨 :: 너비 글자에 맞게
  src/Components/AllergyTags/style.ts
Labels: 리팩토링, 퍼블리싱

#50 ♻️ :: 상태관리 zustand로 하기
  src/Components/VoteType/index.tsx
  src/store/useVoteTypeStore.ts
Labels: 리팩토링

#52 ♻️ :: 투표 표시 상태에 따라서 보이는 페이지 다르게 하기
  src/Components/TextVote/index.tsx
  src/page/votePage/index.tsx
  src/store/useVoteTypeStore.ts
Labels: 리팩토링, 퍼블리싱

#51 ✨ :: 내가 쓴 건의 목록 확인 페이지 퍼블리싱
  src/Pages/MySuggestPage/index.tsx
  src/Pages/MySuggestPage/style.ts
  src/router.tsx
Labels: 퍼블리싱

#46 ✨ :: 공지사항 페이지 퍼블리싱
  src/Components/Notice/Message.tsx
  src/Components/Notice/index.tsx
  src/Components/Notice/style.ts
  src/Pages/NoticePage/index.tsx
  src/Pages/NoticePage/style.ts
  src/router.tsx
Labels: 퍼블리싱

#57 ✨ :: 알레르기 선택 모달 퍼블리싱
  src/Components/AllergyTags/style.ts
  src/Components/ChooseAllergy/index.tsx
  src/Components/ChooseAllergy/style.ts
  src/Components/Logout/index.tsx
  src/Components/Logout/style.ts
  src/Components/MyAllergy/style.ts
  src/router.tsx
Labels: 퍼블리싱

#56 메인페이지 퍼블리싱
  src/Components/LengthMeal/index.tsx
  src/Components/LengthMeal/style.ts
  src/Components/MealList/BreakfastList.tsx
  src/Components/MealList/DinnerList.tsx
  src/Components/MealList/LunchList.tsx
  src/Components/MealTime/MealTime.tsx
  src/Components/MealTime/index.tsx
  src/Components/MealTime/style.ts
  src/Components/WidthMeal/index.tsx
  src/Components/WidthMeal/style.ts
  src/Pages/Main/index.tsx
  src/Pages/Main/style.ts
Labels: 퍼블리싱

#55 💄 :: 메뉴 랭킹 결과 퍼블리싱
  src/Components/DonutGraph/index.tsx
  src/Components/DonutGraph/styled.ts
  src/assets/img/SVG/Crown.svg
Labels: 퍼블리싱
